//
//	@title			azhot
//	@version		1.0.0
//	@description	热搜API聚合服务，提供各大平台热搜数据获取接口
//	@termsOfService	https://github.com/maicarons/azhot
//
//	@contact.name	API Support
//	@contact.url	https://github.com/maicarons/azhot/issues
//	@contact.email
//
//	@license.name	AGPL-3.0
//	@license.url	https://github.com/maicarons/azhot/blob/main/LICENSE
//
//	@host
//	@BasePath		/
//	@schemes		http https

package main

import (
	"api/config"
	"api/db"
	"api/mcp"
	"api/router"
	"api/service"
	"os"

	"api/docs" // docs is generated by Swag CLI, you have to import it.

	"github.com/goccy/go-json"
	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/fiber/v2/log"
	_ "github.com/swaggo/files" // swagger embed files
)

func main() {
	// 全局日志实例
	log.SetOutput(os.Stdout)

	// 加载配置
	cfg, err := config.LoadConfig()
	if err != nil {
		log.Fatal("Failed to load config: ", err)
	}

	// 初始化数据库
	db.InitDBWithConfig(cfg)

	// 初始化服务
	hotSearchService := &service.HotSearchService{}

	// 启动定时任务
	hotSearchService.StartScheduler()

	// 创建Fiber应用实例
	appInstance := fiber.New(fiber.Config{
		// 设置应用名称
		AppName:      "azhot",
		ServerHeader: "",
		JSONEncoder:  json.Marshal,
		JSONDecoder:  json.Unmarshal,
	})

	// 设置路由
	router.SetupRoutes(appInstance, hotSearchService, cfg)

	// 设置MCP路由
	mcp.SetupMCPRoutes(appInstance, hotSearchService, cfg)

	// 动态更新Swagger文档中的Host
	updateSwaggerHost(cfg)

	// 根据配置启动服务器（HTTP或HTTPS）
	if cfg.Server.TLSEnabled && cfg.Server.TLSCertFile != "" && cfg.Server.TLSKeyFile != "" {
		log.Info("Starting HTTPS server on: ", cfg.GetServerAddress())
		log.Fatal(appInstance.ListenTLS(cfg.GetServerAddress(), cfg.Server.TLSCertFile, cfg.Server.TLSKeyFile))
	} else {
		serverAddress := cfg.GetServerAddress()
		log.Info("Starting HTTP server on: ", serverAddress)
		log.Fatal(appInstance.Listen(serverAddress))
	}
}

// updateSwaggerHost 更新Swagger文档中的Host
func updateSwaggerHost(cfg *config.Config) {
	docs.SwaggerInfo.Host = cfg.Server.Host + ":" + cfg.Server.Port

}
